# This is a basic workflow to help you get started with Actions

name: Changelog Action
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 1.15 ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ 1.15 ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew runData
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Buuz135
          author_email: rundata@gmail.com
          message: "Generated Data"
          add: "**.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
